version: "3.7"
services:
  webpack:
    image: node:12
    container_name: webpack-development_container
    tty: true # Keep container running. This option is not available if you build from a dockerfile.
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node-modules
        target: /app/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
    name: webpack_node-modules