FROM nginxinc/nginx-unprivileged:1.18
WORKDIR /app
# We'll mount in the src files for local development
#COPY ./www /app/www
COPY ./server ./server
COPY server/server.conf /etc/nginx/conf.d/default.conf
USER 0
RUN chown -R nginx /etc/nginx/conf.d \
    && chown -R nginx /app \
    && chmod +x ./server/init_app.sh
USER 101
# Note that nginx use port 8080 in nginx-unprivileged
EXPOSE 8080
CMD /bin/sh -c "./server/init_app.sh"